server:
  port: 8080
databases:
  driverName: mysql
  host: 112.74.38.97
  port: 10101
  database: gin-rbac
  username: root
  password: root
  charset: utf8
redis:
  network: tcp
  address: 39.108.133.219:6379
  timeout: 5000